function Hd = FIR_LS_LP(Fs,N,Fpass,Fstop)
%FIR_LP_LEAST_SQUARES Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 8.2 and the Signal Processing Toolbox 6.20.
% Generated on: 25-Jan-2016 13:28:46

% FIR least-squares Lowpass filter designed using the FIRLS function.

% All frequency values are in Hz.
Wpass = 1;      % Passband Weight
Wstop = 1;      % Stopband Weight

% Calculate the coefficients using the FIRLS function.
b  = firls(N, [0 Fpass Fstop Fs/2]/(Fs/2), [1 1 0 0], [Wpass Wstop]);
Hd = dfilt.dffir(b);

% [EOF]